apiVersion: v2
name: spitter
description: Spitter - templating webhook router for Prometheus Alertmanager
type: application

# Chart version; bump on every chart change (SemVer).
version: 0.2.1

# Default image tag deployed by this chart.
appVersion: "0.2.0"

kubeVersion: ">=1.25.0-0"
home: https://github.com/spirilis/spitter
sources:
  - https://github.com/spirilis/spitter
keywords:
  - alertmanager
  - prometheus
  - webhook
  - alerting
maintainers:
  - name: spirilis
    url: https://github.com/spirilis
