{{- if .Values.httpRoute.enabled }}
{{- $fullName := include "spitter.fullname" . }}
{{- $svcPort := .Values.service.port }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "spitter.labels" . | nindent 4 }}
    {{- with .Values.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range (.Values.httpRoute.rules | default (list dict)) }}
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
      {{- with (omit . "backendRefs") }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
{{- end }}
