{{- with .Values.metrics.podMonitor }}
{{- if .enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "spitter.fullname" $ }}
  labels:
    {{- include "spitter.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "spitter.selectorLabels" $ | nindent 6 }}
  podMetricsEndpoints:
    - port: http
      path: {{ $.Values.spitter.metricsPath }}
      {{- with .interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .extraEndpoints }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
