apiVersion: v1
kind: Service
metadata:
  name: {{ include "spitter.fullname" . }}
  labels:
    {{- include "spitter.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.service }}
    {{- if .nodePort.enabled }}
  type: NodePort
    {{- else }}
      {{- if .type }}
  type: {{ .type }}
      {{- else }}
  type: ClusterIP
      {{- end }}
    {{- end }}
    {{- if and .nodePort.enabled .nodePort.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .nodePort.externalTrafficPolicy }}
    {{- end }}
  ports:
    - port: {{ .port }}
      {{- if gt (.targetPort | int) 0 }}
      targetPort: {{ .targetPort | int }}
      {{- else }}
      targetPort: {{ $.Values.spitter.port | int }}
      {{- end }}
      protocol: TCP
      name: http
      appProtocol: http
    {{- if .additionalPorts }}{{- $aidx := 0 }}{{- range .additionalPorts }}{{- $aidx = add1 $aidx }}
    - port: {{ .port }}
      {{- if gt (.targetPort | int) 0 }}
      targetPort: {{ .targetPort | int }}
      {{- else }}
      targetPort: {{ .port }}
      {{- end }}
      {{- if .protocol }}
      protocol: {{ .protocol | quote }}
      {{- else }}
      protocol: TCP
      {{- end }}
      {{- if .name }}
      name: {{ .name | quote }}
      {{- else }}
      name: {{ printf "addl%d" $aidx | quote }}
      {{- end }}
      {{- if .appProtocol }}
      appProtocol: {{ .appProtocol | quote }}
      {{- end }}
    {{- end }}{{- end }}
  {{- end }}
  selector:
    {{- include "spitter.selectorLabels" . | nindent 4 }}
