{{- $svc := .Values.service }}
{{- $external := or (eq $svc.type "NodePort") (eq $svc.type "LoadBalancer") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spitter.fullname" . }}
  labels:
    {{- include "spitter.labels" . | nindent 4 }}
    {{- with $svc.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svc.type }}
  {{- if and $external $svc.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $svc.externalTrafficPolicy }}
  {{- end }}
  {{- if eq $svc.type "LoadBalancer" }}
  {{- with $svc.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with $svc.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
      protocol: TCP
      appProtocol: http
      {{- if and $external $svc.nodePort }}
      nodePort: {{ $svc.nodePort }}
      {{- end }}
    {{- with $svc.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "spitter.selectorLabels" . | nindent 4 }}
